# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx4G
org.gradle.parallel = true

# Minecraft Properties
minecraft_version = 26.1.1
minecraft_version_supported = [26.1,26.1.1]
minecraft_version_lower = 1.21.11
minecraft_version_upper =

# File Name
minecraft_version_name = 26.1
archives_base_name = MoreTorchVariants

# Mod Properties
mod_id = quad-mstv-mtv
mod_name = More Torch Variants (MStV+)
mod_name_short = More Torch Variants
mod_description = This mod adds more variants of the Torch, Soul Torch and Redstone Torch Items.
mod_version = 1.2.4
mod_license = CC-BY-NC-SA-4.0
maven_group = de.pnku

# Dependencies
quad_version = 1.2.3
mstv_version = 1.4.14
mstv_version_id = 3WQJT5yT